### ISSUE TITLE
ReferenceError: uConfig is not defined

### ISSUE THREAD

**Issue by SERVANTSKILL** [Ruuv1337/RTP_IX#10]
hi, im try to use this module but its not work

error code:
`    at _0x572a5e (TeraToolbox\mods\RTPort-master\index.js:1:92680)
    at new objectObject_0x448129 (TeraToolbox\mods\RTPort-master\index.js:1:83095)
    at ModuleManager.load (TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (TeraToolbox\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:215:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1114:10)`

hope can help thankyou

**Comment by SERVANTSKILL** [comment]
messages before say
` [mods] ERROR: Module "RTP" (RTPort 4) could not be loaded!
 [mods] ERROR: Please contact the module's author: https://github.com/Ruuv1337/RTPort/issues
 ReferenceError: uConfig is not defined`

when startup its also write this
```
Failed to update the following module files:
 - index.js
 - ERROR: https://raw.githubusercontent.com/Ruuv1337/RTPort/master/index.js
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by developer
```

**Comment by Ruuv1337** [comment]
fixed

**Comment by SERVANTSKILL** [comment]
hi sorry to open this again but am try to transfer servant skill from 7d pet like the video example but its not work :<

edit: nevermind, after restart its worknow, thank you so much btw :)
