### ISSUE TITLE
Module not working.

### ISSUE THREAD

**Issue by Whutevar** [Ruuv1337/RTP_IX#6]
Hello the module throws an error each time I try to load it. Another thing how to use the 3 days test. I commented out faulty code part to load module and it says no licence key.

**Comment by Ruuv1337** [comment]
hello, attach pls error screenshot.

3-day period begins immediately after the first use "rtp email" command. Instead of "email", you'r enter your mailbox ..

after this you can use other command's

**Comment by Whutevar** [comment]
[12:37:38.088] [Modul] FEHLER: Modul "RTP" (RTPort) konnte nicht geladen werden!
[12:37:38.089] [Modul] FEHLER: Bitte wende dich an den Autor des Moduls: https://github.com/Ruuv1337/RTPort/issues
[12:37:38.091] TypeError: Cannot read property '36' of undefined
    at new RTPort (C:\Users\XXXX\Desktop\Toolbox\mods\RTPort-master\index.js:1:81047)
    at ModuleManager.load (C:\Users\XXXX\Desktop\Toolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at C:\Users\XXXX\Desktop\Toolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\XXXX\Desktop\Toolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (C:\Users\XXXX\Desktop\Toolbox\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:205:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1040:10)

At this part.
`let _0x9338bd = uConfig[0x5][0x24][objectObject_0x1e41('0x10d')];`

**Comment by Whutevar** [comment]
I think its smh related to the config.

**Comment by Ruuv1337** [comment]
I think the same.
Delete the config and try to run.
The module must recreate it.

**Comment by Whutevar** [comment]
Nah issue stays the same smth wrong with `0x24` in `let _0x9338bd = uConfig[0x5][0x24][objectObject_0x1e41('0x10d')];`
Config is recreated but still same error.

**Comment by Ruuv1337** [comment]
Made a few edits. Try it, maybe it will help.

**Comment by Whutevar** [comment]
[18:18:33.554] TypeError: Cannot read property '36' of undefined / 0x24 again 
`let _0x565ef7=uConfig[0x5][0x24][_0x5ba22c[objectObject_0x540b('0xb9')]];` at 1:87951

**Comment by Ruuv1337** [comment]
updated again, the situation has not changed?

**Comment by Whutevar** [comment]
> updated again, the situation has not changed?

Gonna try it again.

**Comment by Whutevar** [comment]
K thx its working now gj.
